version: '3'

services:

  # database containers, one for each db
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database_volume:/data/db
    networks:
      - database_network
    environment:
      MONGO_INITDB_DATABASE: database
  nodeapp:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - database_network
    depends_on:
      - mongo

networks:
  database_network:
    driver: bridge

volumes:
  database_volume:
    driver: "local"

